[package]
name = "tyr"
version = "0.1.0"
authors = ["Johann Bornholdt <github@johann.bornholdt.online>"]

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
config = "0.9"
csv = "1"
dirs = "2"
env_logger = "0.6"
log = "0.4"
serde = "1"
serde_derive = "1"
