[package]
name = "tyr"
version = "0.1.0"
authors = ["Johann Bornholdt <github@johann.bornholdt.online>"]

[dependencies]
csv = "1"
serde = "1"
serde_derive = "1"
chrono = {version = "0.4", features = ["serde"]}
config = "0.9"
log = "0.4"
env_logger = "0.6"
