[package]
name = "tyr"
version = "0.1.0"
authors = ["Johann Bornholdt <github@johann.bornholdt.online>"]

[dependencies]

tyr-lib = {path = "../tyr-lib"}

chrono = {version = "0.4", features = ["serde"]}
env_logger = "0.6"
log = "0.4"
